version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: manga_postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: manga_user
      POSTGRES_PASSWORD: manga_pass
      POSTGRES_DB: manga_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U manga_user -d manga_db']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
